###
# curl -X GET "https://github.com/login/oauth/authorize?client_id=92e48c903bf0b3e8c4f3&redirect_uri=http%3A%2F%2Flocalhost%3A8080%2Fauth%2Fcallback&scope=user+repo&state=fo1Ooc1uofoozeithimah4iaW&allow_signup=false"
# @no-redirect
GET https://github.com/login/oauth/authorize
    ?client_id=92e48c903bf0b3e8c4f3
    &redirect_uri=http://localhost:8080/auth/callback
    &scope=user repo
    &state=fo1Ooc1uofoozeithimah4iaW
    &allow_signup=false

### redirected to: http://localhost:8080/auth/callback?code=3ce16bbcfff7a152295d&state=fo1Ooc1uofoozeithimah4iaW

###
# curl -X POST --location "https://github.com/login/oauth/access_token"
#    -H "Content-Type: application/x-www-form-urlencoded"
#    -d "client_id=92e48c903bf0b3e8c4f3&client_secret={{GITHUB_OAUTH_CLIENT_SECRET}}&code=3ce16bbcfff7a152295d&redirect_uri=http://localhost:8080/auth/callback
POST https://github.com/login/oauth/access_token
Content-Type: application/x-www-form-urlencoded

client_id=92e48c903bf0b3e8c4f3&client_secret={{GITHUB_OAUTH_CLIENT_SECRET}}&code=3ce16bbcfff7a152295d&redirect_uri=http://localhost:8080/auth/callback

### got: access_token=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&scope=repo%2Cuser&token_type=bearer
### already revoked!
