on:
  push:
    branches:
      - master
  workflow_dispatch:
concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true
name: Create release pr
jobs:
  validate-latest-changes:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Cache rust
        id: cache-rust
        uses: actions/cache@v3
        with:
          path: rust/Cargo.toml
          key: ${{ runner.os }}-cargo-toml
      - name: Cargo format and check
        run: | 
          cargo fmt
          cargo check
  release-please:
    needs:
      - validate-latest-changes
    runs-on: ubuntu-latest
    steps:
      - uses: google-github-actions/release-please-action@v3
        with:
          release-type: rust
          package-name: release-please-action
